### ISSUE TITLE
Redundant normalisation 

### ISSUE THREAD

**Issue by ekazakos** [pomonam/AttentionCluster#3]
Hi, 

I believe that the following line is unnecessary:
https://github.com/pomonam/AttentionCluster/blob/7dd11bcc5e4a5572fcd4b14c6450602e922ac9b7/frame_level_models.py#L87

Maybe L101 is unnecessary as well. In my understanding, the paper proposes normalisation only right after the shifting operation. So, I believe that only the normalisation in L99 is useful. 

I can understand the normalisation in L101 as is common to normalise the whole vector and not only within the cluster (similarly to VLAD), but L87 seems pretty redundant. 

Let me know what you think. Thanks.

**Comment by pomonam** [comment]
Hi, 

Thanks for raising a good point. The original paper proposes normalization only right after the shifting, so this code is slightly different from the paper. You are correct; the inter- and outer- normalization is inspired by VLAD. I was experimenting with normalizing before shifting to see the performance difference. You can delete L87 and L101 if you want to do exactly same thing in the paper.

Juhan

**Comment by ekazakos** [comment]
Also the paper explains the 1/sqrt(n) acts as global normalisation, so you either want 1/sqrt(n) or L101 but not both. For L87, I agree that you can leave it or not, for experimentation. 

Vangelis
